version: '3'

services:
    web:
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
      container_name: scheduler_app
      volumes:
        - .:/scheduler_app
      ports:
        - "8000:8000"
      depends_on:
        - db
    
    db:
      image: postgres
      environment:
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_PASSWORD=1234
        - POSTGRES_USER=postgres
        - POSTGRES_HOST=localhost
      
