# Generated by Django 2.2.5 on 2021-03-28 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='num1',
            new_name='m',
        ),
        migrations.RenameField(
            model_name='add',
            old_name='num2',
            new_name='n',
        ),
    ]
